export const INIT_APP = "INIT_APP";

export const SET_MODEL_LAYER_PARAM = "SET_MODEL_LAYER_PARAM";

export const SET_ADD_BLOCK_MODAL_STATUS = "SET_ADD_BLOCK_MODAL_STATUS";
export const SET_CREATE_BLOCK_MODAL_STATUS = "SET_CREATE_BLOCK_MODAL_STATUS";

export const SET_RUNTIME_CONNECTION_MODAL_STATUS =
  "SET_RUNTIME_CONNECTION_MODAL_STATUS";

export const ADD_LAYER_TO_MODEL = "ADD_LAYER_TO_MODEL";

export const SET_RIGHT_CLICK_LOCATION = "SET_RIGHT_CLICK_LOCATION";

export const ADD_MODEL_GRAPH_EDGE = "ADD_MODEL_GRAPH_EDGE";

export const REMOVE_MODEL_GRAPH_ELEMENTS = "REMOVE_MODEL_GRAPH_ELEMENTS";

export const SET_ACTIVE_MODEL_LAYER_ID = "SET_ACTIVE_MODEL_LAYER_ID";

export const SET_TERMINAL_UI_STATE = "SET_TERMINAL_UI_STATE";

export const CREATE_NEW_BLOCK_TYPE = "CREATE_NEW_BLOCK_TYPE";

export const SET_ACTIVE_BLOCK_TYPE = "SET_ACTIVE_BLOCK_TYPE";

export const UPDATE_MODEL_LAYER_CONFIG = "UPDATE_MODEL_LAYER_CONFIG";

export const UPDATE_NODE_POSITION = "UPDATE_NODE_POSITION";

export const UPDATE_DATASET_TRANSFORMERS = "UPDATE_DATASET_TRANSFORMERS";

export const SET_DATASET_MODAL_STATUS = "SET_DATASET_MODAL_STATUS";

export const LOAD_DATA_SET = "LOAD_DATA_SET";

export const UPDATE_MODEL_PARAMETERS = "UPDATE_MODEL_PARAMETERS";

export const SET_MODEL_OPTIMIZER = "SET_MODEL_OPTIMIZER";

export const UPDATE_MODEL_OPTIMIZER_PARAM = "UPDATE_MODEL_OPTIMIZER_PARAM";

export const SET_MODEL_LOSS_FUNCTION = "SET_MODEL_LOSS_FUNCTION";

export const SET_RUNTIME_CONNECTION_STATUS = "SET_RUNTIME_CONNECTION_STATUS";

export const SET_RUNTIME_CONNECTION_PARAMS = "SET_RUNTIME_CINNECTION_PARAMS";

export const SET_RUNTIME_CONNECTION_ERROR = "SET_RUNTIME_CONNECTION_ERROR";
