export const BATCH_SIZE = "BATCH_SIZE";
export const LEARNING_RATE = "LEARNING_RATE";
export const EPOCH_COUNT = "EPOCH_COUNT";

export const LOSS_FUNCTION = "LOSS_FUNCTION";

export const OPTIMIZER = "OPTIMIZER";
export const OPTIMIZER_CONFIG = "OPTIMIZER_CONFIG";
